### ISSUE TITLE
No longer work for Duco 2.0

### ISSUE THREAD

**Issue by idenchik1** [colonelwatch/nonceMiner#5] opened 2021-02-09 14:11 UTC
After 2.0 update mostly reject shares, but result seem right, comparing bad requests with good gived nothing
![image](https://user-images.githubusercontent.com/34679695/107375507-648a3400-6b1b-11eb-8f2a-87537b5b1ef1.png)

**Comment by colonelwatch** [comment] 2021-02-12 07:09
Hello, I investigated this shortly after you mentioned it. As of 2/11/2021, this is reproducible on computers that are capable of achieving at least 2.5 MH/s on a single process, and it is due to a hash-rate limit on the main server. Anything that was mined too fast appears to be rejected.

Anyway, it's out of my control. It will still work though if you run the program on a slower computer or use the recommended number of threads, I guess. I originally recommended 8 or 16 to keep the CPU fed, but now splitting CPU power between more processes than cores helps keep the hashrate per process low. Other than that, I'll keep an ear to the ground for anything I *can* do.

Closing this issue.

**Closed as completed by colonelwatch** 2021-02-12 07:09 UTC
